/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconFaBeer: typeof import('~icons/fa/beer')['default']
    'IconMaterialSymbolsLight:10kOutlineSharp': typeof import('~icons/material-symbols-light/10k-outline-sharp')['default']
    IFaBeer: typeof import('~icons/fa/beer')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
  }
}
